import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { unzipSync, strFromU8 } from 'fflate';
import handler from '../api/admin-backup.js';
import { downloadFullBackup } from '../src/admin-backup.ts';
const originalFetch=globalThis.fetch;
const originalEnv={...process.env};
process.env.ADMIN_HEALTH_TOKEN='test-admin';process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_SECRET_KEY='server-only-test';
const makeRes=()=>({statusCode:0,headers:{},status(c){this.statusCode=c;return this},setHeader(k,v){this.headers[k]=v;return this},json(body){this.body=body;return this},send(body){this.body=body;return this}});
let r=makeRes();await handler({method:'POST',headers:{},body:{action:'catalog'}},r);assert.equal(r.statusCode,401);
r=makeRes();await handler({method:'POST',headers:{authorization:'Bearer test-admin',origin:'https://evil.example',host:'pricetrackph.com'},body:{action:'catalog'}},r);assert.equal(r.statusCode,403);
const catalog={tables:[{name:'products',rowCount:'1001',upperKey:{id:'1001'}}],exportedAt:'2026-10-04T00:00:00Z',storageObjects:0,authUsers:0};
globalThis.fetch=async(url,opts)=> {assert(opts.headers.apikey==='server-only-test');assert(!opts.body.includes('test-admin'));return Response.json(catalog)};
r=makeRes();await handler({method:'POST',headers:{authorization:'Bearer test-admin'},body:{action:'catalog'}},r);assert.equal(r.statusCode,200);assert.equal(r.body.projectRef,'test');assert(!JSON.stringify(r.body).includes('server-only-test'));
const source=readFileSync('.backup/website.zip');
r=makeRes();await handler({method:'POST',headers:{authorization:'Bearer test-admin'},body:{action:'website'}},r);assert.equal(r.statusCode,200);assert.equal(r.body.length,source.length);
let parts=[];let closed=false;let aborted=false;let requests=0;
globalThis.window={showSaveFilePicker:async()=>({createWritable:async()=>({write:async chunk=>parts.push(chunk.slice()),close:async()=>{closed=true},abort:async()=>{aborted=true}})}),addEventListener(){},removeEventListener(){}};
globalThis.localStorage={length:2,key:i=>['pricetrack-test-setting','pricetrack-admin-token'][i],getItem:k=>k==='pricetrack-test-setting'?'true':'secret-token'};
globalThis.fetch=async(_url,opts)=>{requests++;const b=JSON.parse(opts.body);if(b.action==='catalog')return Response.json({...catalog,websiteCommit:'abc',projectRef:'test',environmentVariableNames:['SUPABASE_SECRET_KEY']});if(b.action==='website')return new Response(source);const start=b.after?Number(b.after.id):0;const rows=Array.from({length:Math.min(1000,1001-start)},(_,i)=>JSON.stringify({id:String(start+i+1),title:'Product'}));return Response.json({rows,cursor:{id:String(start+rows.length)}})};
await downloadFullBackup('test-admin',()=>{});assert(closed);assert(!aborted);assert.equal(requests,4);
const bytes=new Uint8Array(Buffer.concat(parts.map(p=>Buffer.from(p))));const files=unzipSync(bytes);assert.equal(strFromU8(files['database/products.ndjson']).trim().split('\n').length,1001);assert.equal(JSON.parse(strFromU8(files['manifest.json'])).complete,true);assert.deepEqual(JSON.parse(strFromU8(files['device-settings.json'])),{'pricetrack-test-setting':'true'});const websiteFiles=unzipSync(files['website.zip']);assert(websiteFiles['src/App.tsx']);assert(websiteFiles['public/icons/icon-192.png']);assert(websiteFiles['backup/restore.py']);assert(!Object.keys(websiteFiles).some(p=>p==='.env'||p.includes('node_modules')));
parts=[];closed=false;aborted=false;
globalThis.fetch=async()=>Response.json({...catalog,tables:[{name:'products',rowCount:'9999',upperKey:null}]});await assert.rejects(downloadFullBackup('test-admin',()=>{}),/Data changed/);assert(aborted);assert(!closed);
globalThis.fetch=originalFetch;process.env=originalEnv;
console.log('Backup auth, origin, secret exclusion, source assets, ZIP pagination/counts, device settings and abort checks passed');
