-- Minimal, private diagnostics retained for 30 days.
create table if not exists public.diagnostic_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check (event_type in (
    'record_success',
    'record_partial',
    'record_failure',
    'duplicate_blocked',
    'variation_count_changed'
  )),
  source text not null default 'record-price' check (char_length(source) between 1 and 80),
  shop_id text,
  product_id text,
  variation_count integer check (variation_count is null or variation_count between 0 and 200),
  recorded_count integer check (recorded_count is null or recorded_count between 0 and 200),
  unchanged_count integer check (unchanged_count is null or unchanged_count between 0 and 200),
  failed_count integer check (failed_count is null or failed_count between 0 and 200),
  status_code integer check (status_code is null or status_code between 100 and 599),
  error_code text check (error_code is null or char_length(error_code) <= 100),
  details jsonb not null default '{}'::jsonb,
  constraint diagnostic_events_details_size check (octet_length(details::text) <= 2048)
);

create index if not exists diagnostic_events_created_at_idx
  on public.diagnostic_events (created_at desc);

create index if not exists diagnostic_events_type_created_at_idx
  on public.diagnostic_events (event_type, created_at desc);

alter table public.diagnostic_events enable row level security;
revoke all on table public.diagnostic_events from anon, authenticated;
grant select, insert, delete on table public.diagnostic_events to service_role;
grant usage, select on sequence public.diagnostic_events_id_seq to service_role;

create or replace function public.delete_expired_diagnostic_events()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count bigint;
begin
  delete from public.diagnostic_events
  where created_at < now() - interval '30 days';
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on function public.delete_expired_diagnostic_events() from public, anon, authenticated;
grant execute on function public.delete_expired_diagnostic_events() to service_role;
