-- Track one lightweight verification per product/day while price_observations
-- continues to store changes only.

alter table public.products
  add column if not exists tracking_enabled boolean not null default true,
  add column if not exists next_check_at timestamptz,
  add column if not exists last_check_attempt_at timestamptz,
  add column if not exists last_checked_at timestamptz,
  add column if not exists last_check_status text,
  add column if not exists consecutive_check_failures integer not null default 0,
  add column if not exists check_lease_until timestamptz;

alter table public.products
  drop constraint if exists products_last_check_status_check;

alter table public.products
  add constraint products_last_check_status_check
  check (last_check_status is null or last_check_status in ('success', 'partial', 'failure'));

update public.products
set next_check_at = coalesce(last_seen_at, now()) + interval '24 hours'
where next_check_at is null;

create index if not exists products_due_daily_check_idx
  on public.products (next_check_at)
  where tracking_enabled and is_active and platform = 'shopee';

create table if not exists public.product_daily_checks (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  checked_date date not null,
  checked_at timestamptz not null default now(),
  source text not null check (source in ('extension', 'scheduled_collector')),
  status text not null check (status in ('success', 'partial', 'failure')),
  variation_count integer not null default 0 check (variation_count between 0 and 200),
  changed_count integer not null default 0 check (changed_count between 0 and 200),
  unchanged_count integer not null default 0 check (unchanged_count between 0 and 200),
  failed_count integer not null default 0 check (failed_count between 0 and 200),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_daily_checks_product_date_unique unique (product_id, checked_date),
  constraint product_daily_checks_metadata_size check (octet_length(metadata::text) <= 2048)
);

create index if not exists product_daily_checks_product_date_idx
  on public.product_daily_checks (product_id, checked_date desc);

alter table public.product_daily_checks enable row level security;

drop policy if exists "Public can read product daily checks" on public.product_daily_checks;
create policy "Public can read product daily checks"
  on public.product_daily_checks
  for select
  to anon, authenticated
  using (true);

revoke all on table public.product_daily_checks from anon, authenticated;
grant select on table public.product_daily_checks to anon, authenticated;
grant select, insert, update, delete on table public.product_daily_checks to service_role;
grant usage, select on sequence public.product_daily_checks_id_seq to service_role;

create or replace function public.claim_due_product_checks(p_batch_size integer default 10)
returns table (
  product_id bigint,
  shop_id text,
  external_product_id text,
  product_url text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with due as (
    select p.id
    from public.products p
    where p.platform = 'shopee'
      and p.is_active
      and p.tracking_enabled
      and coalesce(p.next_check_at, now()) <= now()
      and (p.check_lease_until is null or p.check_lease_until < now())
      and not exists (
        select 1
        from public.product_daily_checks c
        where c.product_id = p.id
          and c.checked_date = (now() at time zone 'Asia/Manila')::date
          and c.status = 'success'
      )
    order by p.next_check_at nulls first, p.id
    limit greatest(1, least(coalesce(p_batch_size, 10), 25))
    for update skip locked
  ), leased as (
    update public.products p
    set check_lease_until = now() + interval '10 minutes'
    from due
    where p.id = due.id
    returning p.id, p.external_shop_id, p.external_product_id, p.product_url
  )
  select leased.id, leased.external_shop_id, leased.external_product_id, leased.product_url
  from leased;
end;
$$;

revoke all on function public.claim_due_product_checks(integer) from public, anon, authenticated;
grant execute on function public.claim_due_product_checks(integer) to service_role;

create or replace function public.mark_product_check(
  p_product_id bigint,
  p_checked_date date,
  p_checked_at timestamptz,
  p_source text,
  p_status text,
  p_variation_count integer,
  p_changed_count integer,
  p_unchanged_count integer,
  p_failed_count integer,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_source not in ('extension', 'scheduled_collector')
     or p_status not in ('success', 'partial', 'failure') then
    raise exception 'Invalid product check source or status';
  end if;

  insert into public.product_daily_checks (
    product_id, checked_date, checked_at, source, status,
    variation_count, changed_count, unchanged_count, failed_count, metadata
  ) values (
    p_product_id, p_checked_date, p_checked_at, p_source, p_status,
    greatest(0, least(coalesce(p_variation_count, 0), 200)),
    greatest(0, least(coalesce(p_changed_count, 0), 200)),
    greatest(0, least(coalesce(p_unchanged_count, 0), 200)),
    greatest(0, least(coalesce(p_failed_count, 0), 200)),
    coalesce(p_metadata, '{}'::jsonb)
  )
  on conflict (product_id, checked_date) do update
  set checked_at = greatest(product_daily_checks.checked_at, excluded.checked_at),
      source = case when product_daily_checks.status = 'success' then product_daily_checks.source else excluded.source end,
      status = case when product_daily_checks.status = 'success' then 'success' else excluded.status end,
      variation_count = case when product_daily_checks.status = 'success' then product_daily_checks.variation_count else excluded.variation_count end,
      changed_count = case when product_daily_checks.status = 'success' then product_daily_checks.changed_count else excluded.changed_count end,
      unchanged_count = case when product_daily_checks.status = 'success' then product_daily_checks.unchanged_count else excluded.unchanged_count end,
      failed_count = case when product_daily_checks.status = 'success' then product_daily_checks.failed_count else excluded.failed_count end,
      metadata = case when product_daily_checks.status = 'success' then product_daily_checks.metadata else excluded.metadata end,
      updated_at = now();

  update public.products
  set last_check_attempt_at = p_checked_at,
      last_checked_at = case when p_status = 'success' then p_checked_at else last_checked_at end,
      last_check_status = p_status,
      consecutive_check_failures = case when p_status = 'success' then 0 else consecutive_check_failures + 1 end,
      next_check_at = case
        when p_status = 'success' then p_checked_at + interval '24 hours'
        else now() + interval '6 hours'
      end,
      check_lease_until = null
  where id = p_product_id;
end;
$$;

revoke all on function public.mark_product_check(bigint,date,timestamptz,text,text,integer,integer,integer,integer,jsonb)
  from public, anon, authenticated;
grant execute on function public.mark_product_check(bigint,date,timestamptz,text,text,integer,integer,integer,integer,jsonb)
  to service_role;
